"""AI-First Dynamic Planner — LLM-driven workflow generation.

Instead of hardcoded phase ordering, the AIPlanner:
1. Receives user requirements and project context
2. Reads the ProcessRegistry catalog (what the system can do)
3. Uses an LLM to generate a dynamic execution plan
4. Validates the plan against the registry
5. Supports re-planning on failure

This replaces:
- create_default_workflow() — hardcoded 4-phase pipeline
- PHASE_SKILL_PLAYBOOK — hardcoded agent-skill mappings
- _generate_workflow_plan() — constrained to exactly 4 canonical phases
"""

from __future__ import annotations

import json
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Any

from ..utils.logging import get_logger
from .artifact import ArtifactType
from .process_md_adapter import ProcessMdAdapter
from .process_registry import ProcessRegistry

logger = get_logger(__name__)


@dataclass
class PlanStep:
    """A single step in an execution plan."""

    process_id: str
    agent: str
    rationale: str
    input_mapping: dict[str, str] = field(default_factory=dict)
    depends_on_steps: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "process_id": self.process_id,
            "agent": self.agent,
            "rationale": self.rationale,
            "input_mapping": self.input_mapping,
            "depends_on_steps": self.depends_on_steps,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "PlanStep":
        return cls(
            process_id=str(data.get("process_id", "")),
            agent=str(data.get("agent", "")),
            rationale=str(data.get("rationale", "")),
            input_mapping=dict(data.get("input_mapping", {})),
            depends_on_steps=list(data.get("depends_on_steps", [])),
        )


@dataclass
class ExecutionPlan:
    """A complete execution plan generated by the AI planner."""

    goal: str
    steps: list[PlanStep]
    reasoning: str
    metadata: dict[str, Any] = field(default_factory=dict)

    def validate(self, registry: ProcessRegistry | None = None) -> list[str]:
        """Validate the plan structure. Returns list of error messages.

        If registry is provided, also validates artifact dependency chains.
        """
        errors: list[str] = []
        step_ids = {s.process_id for s in self.steps}

        # Check for references to non-existent steps
        for step in self.steps:
            for dep in step.depends_on_steps:
                if dep not in step_ids:
                    errors.append(f"Step '{step.process_id}' depends on nonexistent step '{dep}'")

        # Check for circular dependencies
        if self._has_cycle():
            errors.append("Circular dependency detected in plan steps")

        # Validate artifact dependency chains (if registry provided)
        if registry is not None:
            self._validate_artifact_chains(registry, step_ids, errors)

        return errors

    def _validate_artifact_chains(
        self,
        registry: ProcessRegistry,
        step_ids: set[str],
        errors: list[str],
    ) -> None:
        """Check that all artifact dependencies are satisfied by preceding steps."""
        produced_artifacts: set[ArtifactType] = set()

        for step in self.steps:
            proc = registry.get(step.process_id)
            if proc is None:
                continue

            # Check if this step's artifact dependencies are met
            for dep_art in proc.depends_on_artifacts:
                if dep_art not in produced_artifacts:
                    # Check if a preceding step produces this artifact
                    producer_found = False
                    for prev_step in self.steps:
                        if prev_step.process_id == step.process_id:
                            break  # Reached current step, stop searching
                        prev_proc = registry.get(prev_step.process_id)
                        if prev_proc and dep_art in prev_proc.output_artifact_types:
                            producer_found = True
                            break

                    if not producer_found:
                        errors.append(
                            f"Step '{step.process_id}' requires artifact {dep_art.value} "
                            f"but no preceding step produces it. Missing prerequisite process."
                        )

            # Track artifacts produced by this step
            for art_type in proc.output_artifact_types:
                produced_artifacts.add(art_type)

    def execution_order(self) -> list[PlanStep]:
        """Return steps in topologically sorted execution order."""
        step_map = {s.process_id: s for s in self.steps}
        in_degree: dict[str, int] = {s.process_id: 0 for s in self.steps}
        graph: dict[str, list[str]] = defaultdict(list)

        for step in self.steps:
            for dep in step.depends_on_steps:
                if dep in step_map:
                    graph[dep].append(step.process_id)
                    in_degree[step.process_id] += 1

        queue = sorted([pid for pid, deg in in_degree.items() if deg == 0])
        result: list[PlanStep] = []

        while queue:
            current = queue.pop(0)
            result.append(step_map[current])
            for dependent in sorted(graph[current]):
                in_degree[dependent] -= 1
                if in_degree[dependent] == 0:
                    queue.append(dependent)

        return result

    def _has_cycle(self) -> bool:
        """Detect cycles using topological sort."""
        ordered = self.execution_order()
        return len(ordered) != len(self.steps)


@dataclass
class PlannerContext:
    """Context for the AI planner to make decisions."""

    user_requirements: str
    available_artifacts: dict[ArtifactType, str] = field(default_factory=dict)
    constraints: list[str] = field(default_factory=list)
    goal_artifacts: list[ArtifactType] = field(default_factory=list)
    project_name: str = ""
    history: list[dict[str, Any]] = field(default_factory=list)


# The prompt template for the AI planner
PLANNER_SYSTEM_PROMPT = """\
You are an AI workflow planner for a software development team.

Your job: Given user requirements and a catalog of available processes, generate
an optimal execution plan. You are NOT constrained to any fixed phase ordering.
Select only the processes that are actually needed for the given requirements.

## Available Processes Catalog
{catalog}

## Rules
1. Each step must reference a process_id from the catalog exactly.
2. Agent must be one of the agent_roles listed for that process.
3. depends_on_steps lists process_ids of steps that MUST complete first.
4. Order steps so that artifact dependencies are satisfied before use.
5. Skip processes whose output artifacts are already available.
6. Include a brief rationale explaining why each step is needed.
7. For complex projects (multiple subsystems, integrations, authentication, etc.),
   include ALL deep workflow phases: deep_product_workflow -> deep_architecture_workflow -> deep_developer_workflow.
8. For simple projects (single-purpose scripts, small utilities), you may skip
   phases that are not strictly necessary.
9. MANDATORY DEPENDENCY CHAIN: If a step produces artifact A and another step
   requires artifact A, the producer MUST come before the consumer in depends_on_steps.
10. COMMON DEPENDENCY CHAIN for software projects:
    - deep_product_workflow produces REQUIREMENTS and SYSTEM_REQUIREMENTS
    - deep_architecture_workflow requires REQUIREMENTS and produces ARCHITECTURE_DESIGN
    - deep_developer_workflow requires ARCHITECTURE_DESIGN and produces SOURCE_CODE
    - deep_testing_workflow requires SOURCE_CODE and produces TEST_RESULTS
    - NEVER skip a prerequisite step - always include the full chain
11. ARTIFACT FLOW ANALYSIS: Before generating the plan, trace the artifact chain:
    - What final artifact is needed? (e.g., SOURCE_CODE for a working app)
    - What produces it? (e.g., deep_developer_workflow)
    - What does that require? (e.g., ARCHITECTURE_DESIGN)
    - What produces THAT? (e.g., deep_architecture_workflow)
    - Continue until you reach the root (raw requirements)
    - Include ALL steps in this chain
12. PROJECT COMPLEXITY ASSESSMENT: Analyze the requirements to determine complexity:
    - Simple: Single-purpose script, no UI, no data persistence (< 3 features)
    - Medium: Web app with UI, basic CRUD, 3-10 features
    - Complex: Multi-subsystem, authentication, APIs, integrations, > 10 features
    - For Medium/Complex projects: ALWAYS include full deep workflow chain
13. INPUT MAPPING: Set input_mapping to map artifact IDs from previous steps
    to the expected input keys of the current step.

## Artifact Types and Their Producers
- REQUIREMENTS: produced by deep_product_workflow
- SYSTEM_REQUIREMENTS: produced by deep_product_workflow
- ARCHITECTURE_DESIGN: produced by deep_architecture_workflow
- SUBSYSTEM_DESIGNS: produced by deep_architecture_workflow
- SOURCE_CODE: produced by deep_developer_workflow
- TEST_RESULTS: produced by deep_testing_workflow

## Example Plans

GOOD (correct dependency chain for a Todo App):
```json
{{
  "goal": "Build a Todo web application with user authentication",
  "reasoning": "Medium complexity: needs UI, auth, data persistence. Full deep workflow required.",
  "steps": [
    {{
      "process_id": "deep_product_workflow",
      "agent": "product_manager",
      "rationale": "Produces REQUIREMENTS and SYSTEM_REQUIREMENTS from raw requirements",
      "input_mapping": {{"raw_requirements": "user_input"}},
      "depends_on_steps": []
    }},
    {{
      "process_id": "deep_architecture_workflow",
      "agent": "architect",
      "rationale": "Needs REQUIREMENTS from deep_product_workflow to produce ARCHITECTURE_DESIGN",
      "input_mapping": {{"requirements": "<artifact_id_from_deep_product_workflow>"}},
      "depends_on_steps": ["deep_product_workflow"]
    }},
    {{
      "process_id": "deep_developer_workflow",
      "agent": "developer",
      "rationale": "Needs ARCHITECTURE_DESIGN from deep_architecture_workflow to produce SOURCE_CODE",
      "input_mapping": {{"architecture": "<artifact_id_from_deep_architecture_workflow>"}},
      "depends_on_steps": ["deep_architecture_workflow"]
    }}
  ]
}}
```

GOOD (Simple script project - can skip some phases):
```json
{{
  "goal": "Create a Python script to convert PDF to text",
  "reasoning": "Simple single-purpose utility. Only needs code generation, no architecture design needed.",
  "steps": [
    {{
      "process_id": "code_generation",
      "agent": "developer",
      "rationale": "Direct code generation from requirements for simple script",
      "input_mapping": {{"raw_requirements": "user_input"}},
      "depends_on_steps": []
    }}
  ]
}}
```

BAD (missing dependency chain - DO NOT DO THIS):
```
{{
  "goal": "Build a web application",
  "steps": [
    {{
      "process_id": "deep_architecture_workflow",
      "agent": "architect",
      "rationale": "...",
      "depends_on_steps": []
    }},
    {{
      "process_id": "deep_developer_workflow",
      "agent": "developer",
      "rationale": "...",
      "depends_on_steps": ["deep_architecture_workflow"]
    }}
  ]
}}
```
This is BAD because deep_architecture_workflow requires REQUIREMENTS, but no step produces it.

BAD (wrong dependency direction):
```
{{
  "steps": [
    {{
      "process_id": "deep_developer_workflow",
      "agent": "developer",
      "depends_on_steps": []
    }},
    {{
      "process_id": "deep_architecture_workflow",
      "agent": "architect",
      "depends_on_steps": ["deep_developer_workflow"]
    }}
  ]
}}
```
This is BAD because developer needs architecture, not the reverse.

## Output Format
Return STRICT JSON only (no markdown fences, no reasoning prefix):
{{
  "goal": "...",
  "reasoning": "...",
  "steps": [
    {{
      "process_id": "...",
      "agent": "...",
      "rationale": "...",
      "input_mapping": {{}},
      "depends_on_steps": []
    }}
  ]
}}
"""

REPLAN_SYSTEM_PROMPT = """\
You are an AI workflow planner. A previous execution plan failed at a specific step.
Generate a recovery plan that resumes from the point of failure.

## Original Plan
{original_plan}

## Failed Step
Process: {failed_step_id}
Error: {error}

## Already Completed Artifacts
{completed_artifacts}

## Available Processes Catalog
{catalog}

## Rules
1. Do NOT re-execute steps whose output artifacts already exist.
2. Start from the failed step (retry or use an alternative process).
3. Include all remaining steps needed to reach the goal.
4. Return STRICT JSON in the same format as the original plan.
"""


class AIPlanner:
    """AI-driven workflow planner that generates execution plans dynamically.

    Instead of following a fixed pipeline, the AIPlanner:
    1. Reads the ProcessRegistry to understand all available capabilities
    2. Uses an LLM to select and order processes based on actual requirements
    3. Validates the generated plan against the registry
    4. Supports re-planning when steps fail
    """

    def __init__(
        self,
        registry: ProcessRegistry,
        llm_config: dict[str, Any] | None = None,
        md_adapter: ProcessMdAdapter | None = None,
    ) -> None:
        self.registry = registry
        self.md_adapter = md_adapter
        self.llm_config = llm_config or {}
        self._llm_client: Any | None = None

    def generate_plan(
        self,
        context: PlannerContext,
        selected_process_id: str | None = None,
    ) -> ExecutionPlan:
        """Generate an execution plan from requirements and context.

        If selected_process_id is provided, the plan is constrained to follow
        that process template. Otherwise, the LLM dynamically composes a plan.

        Uses LLM to dynamically compose a workflow. Falls back to
        dependency-chain resolution if LLM fails.
        """
        catalog = json.dumps(self.registry.to_llm_catalog(), indent=2, ensure_ascii=False)
        selected_process = None

        # Step 1: Select process if ID provided or if md_adapter is available
        if selected_process_id and self.md_adapter:
            descriptor = self.md_adapter.get_descriptor(selected_process_id)
            if descriptor:
                # Look up the underlying ProcessDefinition from the md repo
                for proc in self.md_adapter.md_repo.list_processes():
                    if f"md_process_{proc.process_id}" == descriptor.id:
                        selected_process = proc
                        break
        elif not selected_process_id and self.md_adapter:
            # Auto-select based on requirements
            selection = self.md_adapter.select_process(context.user_requirements)
            if selection:
                selected_process = selection.process
                selected_process_id = selection.process.process_id
                logger.info("Auto-selected process: %s (score=%.1f)", selected_process_id, selection.score)

        messages = self._build_plan_messages(context, catalog, selected_process)

        try:
            logger.info("generate_plan: calling _call_llm...")
            response = self._call_llm(messages)
            logger.info("generate_plan: LLM returned, length=%d", len(response) if response else 0)
            logger.info("generate_plan: calling _parse_plan_response...")
            plan = self._parse_plan_response(response)
            logger.info(
                "AI plan generated: goal=%s steps=%d process=%s",
                plan.goal,
                len(plan.steps),
                selected_process_id or "auto",
            )
            return plan
        except Exception as exc:
            logger.error("generate_plan: exception: %s: %s", type(exc).__name__, exc)
            # DISABLED FALLBACK: AI-First requires LLM-generated plan
            raise RuntimeError(
                f"AI planner LLM failed and fallback is disabled (AI-First mode). "
                f"Error: {exc}. Check LLM API connectivity, model availability, and prompt validity."
            ) from exc

    def replan(
        self,
        original_plan: ExecutionPlan,
        failed_step_id: str,
        error: str,
        completed_artifacts: dict[ArtifactType, str],
    ) -> ExecutionPlan:
        """Generate a recovery plan after a step failure."""
        catalog = json.dumps(self.registry.to_llm_catalog(), indent=2, ensure_ascii=False)
        original_json = json.dumps(
            {"goal": original_plan.goal, "steps": [s.to_dict() for s in original_plan.steps]},
            indent=2,
        )
        artifacts_str = json.dumps(
            {k.value: v for k, v in completed_artifacts.items()},
            indent=2,
        )

        replan_content = REPLAN_SYSTEM_PROMPT.format(
            original_plan=original_json,
            failed_step_id=failed_step_id,
            error=error,
            completed_artifacts=artifacts_str,
            catalog=catalog,
        )

        messages = [
            {"role": "system", "content": "You are an AI workflow planner."},
            {"role": "user", "content": replan_content},
        ]

        try:
            response = self._call_llm(messages)
            plan = self._parse_plan_response(response)
            logger.info("Recovery plan generated: steps=%d", len(plan.steps))
            return plan
        except Exception as exc:
            # DISABLED FALLBACK: AI-First requires LLM-generated replan
            raise RuntimeError(
                f"AI replan LLM failed and fallback is disabled (AI-First mode). "
                f"Original plan failed at step '{failed_step_id}'. Error: {exc}. "
                f"Check LLM API, model availability, and error context."
            ) from exc

    def validate_plan(self, plan: ExecutionPlan) -> list[str]:
        """Validate a plan against the process registry."""
        errors = plan.validate(self.registry)

        for step in plan.steps:
            proc = self.registry.get(step.process_id)
            if proc is None:
                errors.append(f"Process '{step.process_id}' not found in registry")
            elif step.agent not in proc.agent_roles:
                errors.append(
                    f"Agent '{step.agent}' is not valid for process '{step.process_id}'. "
                    f"Valid agents: {proc.agent_roles}"
                )

        return errors

    def _build_plan_messages(
        self,
        context: PlannerContext,
        catalog: str,
        selected_process: Any = None,
    ) -> list[dict[str, str]]:
        """Build system + user messages for the LLM."""
        # If a process is selected, add it to the system prompt
        if selected_process is not None:
            from .process_md_repository import ProcessDefinition

            if isinstance(selected_process, ProcessDefinition):
                process_template = selected_process.render_for_prompt()
                process_section = (
                    "\n\n## SELECTED DEVELOPMENT PROCESS (MANDATORY)\n"
                    "You MUST follow the process template below. This is an organizational requirement.\n\n"
                    f"{process_template}\n\n"
                    "Process Rules:\n"
                    "- Your plan MUST include ALL steps defined in the process template.\n"
                    "- Step ordering MUST follow the process template's sequence.\n"
                    "- Participating agents for each step MUST be from the template's specified agents.\n"
                    "- You can add sub-steps within each process step for more granular planning.\n"
                    "- Do NOT skip any process step.\n"
                )
                system = PLANNER_SYSTEM_PROMPT.format(catalog=catalog) + process_section
            else:
                system = PLANNER_SYSTEM_PROMPT.format(catalog=catalog)
        else:
            system = PLANNER_SYSTEM_PROMPT.format(catalog=catalog)

        user_parts: list[str] = []

        if context.available_artifacts:
            user_parts.append("## Already Available Artifacts")
            for art_type, art_id in context.available_artifacts.items():
                user_parts.append(f"- {art_type.value}: {art_id}")
            user_parts.append("\nSkip processes that would re-create these.")

        if context.constraints:
            user_parts.append("## Additional Constraints")
            for c in context.constraints:
                user_parts.append(f"- {c}")

        if context.goal_artifacts:
            user_parts.append("## Goal Artifacts")
            user_parts.append("The plan must produce these artifact types:")
            for g in context.goal_artifacts:
                user_parts.append(f"- {g.value}")

        user_parts.append(f"## User Requirements\n{context.user_requirements}")

        return [
            {"role": "system", "content": system},
            {"role": "user", "content": "\n\n".join(user_parts)},
        ]

    def _parse_plan_response(self, response: str) -> ExecutionPlan:
        """Parse LLM response into an ExecutionPlan."""
        logger.info("_parse_plan_response: response length=%d, head=%s...", len(response), response[:100])
        # Handle reasoning model responses: find largest valid JSON
        payload = self._extract_json(response)
        logger.info("_parse_plan_response: JSON extracted, keys=%s", list(payload.keys()) if isinstance(payload, dict) else "NOT DICT")

        steps = []
        for step_data in payload.get("steps", []):
            steps.append(PlanStep.from_dict(step_data))

        return ExecutionPlan(
            goal=str(payload.get("goal", "")),
            steps=steps,
            reasoning=str(payload.get("reasoning", "")),
        )

    def _extract_json(self, text: str) -> dict[str, Any]:
        """Extract the largest valid JSON object from text.

        Handles reasoning model outputs that prefix JSON with thinking text.
        """

        # Try direct parse first
        text = text.strip()
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            pass

        # Find all { positions and try to parse from each
        candidates: list[tuple[int, dict[str, Any]]] = []
        for i, ch in enumerate(text):
            if ch == "{":
                try:
                    decoder = json.JSONDecoder()
                    obj, end = decoder.raw_decode(text, i)
                    if isinstance(obj, dict):
                        candidates.append((end - i, obj))
                except (json.JSONDecodeError, ValueError):
                    continue

        if candidates:
            # Return the largest valid JSON object
            candidates.sort(key=lambda x: x[0], reverse=True)
            return candidates[0][1]

        raise ValueError(f"No valid JSON found in response: {text[:200]}...")

    def _call_llm(self, messages: list[dict[str, str]]) -> str:
        """Call the LLM with the given messages.

        When created via from_llm_client(), this calls LLMClient.complete().
        Override in tests or use from_llm_client() for production.
        """
        if self._llm_client is not None:
            return self._llm_client.complete(messages)
        raise NotImplementedError(
            "AIPlanner._call_llm must be implemented or mocked. "
            "Use AIPlanner.from_llm_client() to create a configured instance."
        )

    def _fallback_plan(self, context: PlannerContext) -> ExecutionPlan:
        """Generate a plan using registry dependency resolution when LLM fails."""
        available = set(context.available_artifacts.keys())

        # Determine goal artifacts
        goals = context.goal_artifacts
        if not goals:
            # Default: try to produce source code (full SDLC)
            goals = [ArtifactType.SOURCE_CODE]

        all_steps: list[PlanStep] = []
        seen_ids: set[str] = set()

        for goal in goals:
            chain = self.registry.resolve_dependency_chain(goal, available.copy())
            for proc in chain:
                if proc.id not in seen_ids:
                    seen_ids.add(proc.id)
                    # Find dependencies that are in our chain
                    dep_step_ids = []
                    for dep_art in proc.depends_on_artifacts:
                        if dep_art not in available:
                            producers = self.registry.find_producers(dep_art)
                            for p in producers:
                                if p.id in seen_ids:
                                    dep_step_ids.append(p.id)
                                    break

                    all_steps.append(
                        PlanStep(
                            process_id=proc.id,
                            agent=proc.agent_roles[0] if proc.agent_roles else "developer",
                            rationale=f"Fallback: needed to produce {[a.value for a in proc.output_artifact_types]}",
                            input_mapping={},
                            depends_on_steps=dep_step_ids,
                        )
                    )

        return ExecutionPlan(
            goal="Fallback plan from dependency resolution",
            steps=all_steps,
            reasoning="Generated via registry dependency chain (LLM unavailable)",
        )

    @classmethod
    def from_llm_client(
        cls,
        registry: ProcessRegistry,
        llm_client: Any,
    ) -> "AIPlanner":
        """Create an AIPlanner with a real LLM client.

        The llm_client must support .complete(messages) -> str.
        """
        planner = cls(registry=registry)
        planner._llm_client = llm_client
        return planner

    @classmethod
    def with_llm_client(
        cls,
        registry: ProcessRegistry,
        llm_client: Any,
    ) -> "AIPlanner":
        """Alias for from_llm_client (backward compat)."""
        return cls.from_llm_client(registry, llm_client)
